events {
    worker_connections 1024;
}

http {
    server {
        listen 0.0.0.0:12780;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location = /api/token {
            proxy_pass http://127.0.0.1:8081/api/token;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }

        location / {
            try_files $uri /index.html;
        }
    }
}